[package]
name = "removent-media-capture"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
screencapturekit = "0.3"
core-media-rs = "0.3"
core-foundation = "0.10"
core-video-rs = "0.3"
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
